CREATE TABLE anime
(
    anime_id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version       INTEGER,
    cover_image   VARCHAR(255),
    start_date    date,
    average_score DOUBLE PRECISION,
    popularity    DOUBLE PRECISION,
    review_status VARCHAR(255),
    title_native  VARCHAR(255),
    title_romaji  VARCHAR(255),
    title_en      VARCHAR(255),
    title_cn      VARCHAR(255),
    CONSTRAINT pk_anime PRIMARY KEY (anime_id)
);

CREATE TABLE mapping
(
    mapping_id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version               INTEGER,
    anime_id              BIGINT,
    source_platform       VARCHAR(255),
    platform_id           VARCHAR(255),
    raw_score             DOUBLE PRECISION,
    normalized_score      DOUBLE PRECISION,
    raw_popularity        DOUBLE PRECISION,
    normalized_popularity DOUBLE PRECISION,
    update_time           TIMESTAMP WITHOUT TIME ZONE,
    title_native          VARCHAR(255),
    title_romaji          VARCHAR(255),
    title_en              VARCHAR(255),
    title_cn              VARCHAR(255),
    cover_image           VARCHAR(255),
    start_date            date,
    CONSTRAINT pk_mapping PRIMARY KEY (mapping_id)
);

ALTER TABLE mapping
    ADD CONSTRAINT uc_mapping_source_platform UNIQUE (source_platform, platform_id);

ALTER TABLE mapping
    ADD CONSTRAINT FK_MAPPING_ON_ANIME FOREIGN KEY (anime_id) REFERENCES anime (anime_id);
