spring:
  application:
    name: meta-anime-backend

  datasource:
    driver-class-name: org.postgresql.Driver

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${oidc.issuer}

platform:
  bangumi:
    popularity-multiplier: 166.7
    score-weight: 2
    score-mean: 5.81
    score-std: 1.12
  anilist:
    popularity-multiplier: 11.1
    score-weight: 1
    score-mean: 67.2
    score-std: 9.67
  myanimelist:
    popularity-multiplier: 1.0
    score-weight: 1
    score-mean: 6.99
    score-std: 0.766
