spring:
  application:
    name: meta-anime-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/meta-anime
    username: jim
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${oidc.issuer}

mal:
  client-id: ${MAL_CLIENT_ID}

oidc:
  issuer: ${OIDC_ISSUER}
  client-id: ${OIDC_CLIENT_ID}
