packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  vue-demi: true

catalog:
  # dependencies
  "@element-plus/icons-vue": ^2.3.2
  "@tailwindcss/vite": ^4.2.4
  "element-plus": ^2.14.0
  "tailwindcss": ^4.2.4
  "vue": ^3.5.34
  "vue-router": ^5.0.6

  # dev dependencies
  "@vitejs/plugin-vue": ^6.0.6
  "unplugin-auto-import": ^21.0.0
  "unplugin-vue-components": ^32.0.0
  vite: ^8.0.11
  vue-tsc: ^3.2.8
